# FROM --platform=arm64 docker.io/library/gradle:jdk11
# In dev we use x86, in prod we use arm64 (raspberry)
FROM --platform=amd64 docker.io/library/gradle:jdk11
ENV GRADLE_USER_HOME=/src/.gradle
EXPOSE 8080/tcp
USER 1000
WORKDIR /src
CMD ["/src/gradlew", "bootRun"]